run:
  concurrency: 4
  build-tags:
    - integ
    - integfuzz

linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - exportloopref
    - gocritic
    - gofumpt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - gci
    - gosec
    - asciicheck
    - prealloc
    - predeclared
    - makezero
  fast: false

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    # 如果需要启用 shadow 检查，可添加：
    # enable:
    #   - shadow
    #   - fieldalignment  # 如需替换 maligned 的功能
  misspell:
    locale: US
    ignore-words:
      - cancelled
      - marshalled
  lll:
    line-length: 160
    tab-width: 1
  gocritic:
    disabled-checks:
      - exitAfterDefer
  unparam:
    check-exported: false
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/fatedier/frp/)
  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G102
      - G112
      - G306
      - G401
      - G402
      - G404
      - G501

issues:
  exclude-rules:
    # Exclude some linters from running on test files.
    - path: _test\.go$|^tests/|^samples/
      linters:
        - errcheck
    - linters:
        - revive
        - stylecheck
      text: "use underscores in Go names"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - unparam
      text: "is always false"
  exclude-dirs:
    - genfiles$
    - vendor$
    - bin$
  exclude-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
  exclude-use-default: true
